# Generated by Django 4.0.3 on 2022-04-09 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('grade_during_BKBW', models.CharField(blank=True, default='', max_length=10)),
                ('birthdate', models.CharField(blank=True, max_length=12)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('apartment', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=5)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50)),
                ('graduation_status', models.CharField(choices=[('GR', 'Graduated'), ('DR', 'Dropped'), ('IP', 'In Progress')], default='GR', max_length=2)),
                ('active_alum', models.CharField(blank=True, max_length=30)),
                ('school', models.CharField(blank=True, max_length=30)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('instructors', models.CharField(blank=True, max_length=100)),
                ('media_consent', models.BooleanField(blank=True, default=False)),
                ('program_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('cell_phone', models.CharField(blank=True, max_length=12)),
                ('home_phone', models.CharField(blank=True, max_length=12)),
                ('work_phone', models.CharField(blank=True, max_length=12)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('do_not_solicit', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.student')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parents', models.ManyToManyField(blank=True, to='SMS.parent')),
            ],
        ),
    ]
