# Generated by Django 4.0.3 on 2022-04-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0002_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
